apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: example-mysql-jsonnet
  name: example-mysql-jsonnet
  namespace: minikube-mysql
spec:
  clusterIP: None
  loadBalancerSourceRanges: []
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    name: example-mysql
  type: ClusterIP
