apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: ?{base64:targets/all-glob/mysql/subvars@var1.password:4d310147}
  MYSQL_ROOT_PASSWORD_SHA256: ?{base64:targets/all-glob/mysql/subvars@var2.password_sha256:4d310147}
kind: Secret
metadata:
  annotations: {}
  labels:
    name: glob_instance
  name: glob_instance
  namespace: all-glob
type: Opaque
